Repository vtex-apps/minicart, pull requests merged in 2019-02, with the labels that each got.

#93 Implement an optimistic strategy to the minicart
  CHANGELOG.md
  manifest.json
  react/LinkState.js
  react/components/MiniCartContent.js
  react/components/MiniCartFooter.js
  react/components/MiniCartItem.js
  react/components/Sidebar.js
  react/index.js
  react/package.json
  react/yarn.lock
Labels: enhancement

#76 Improve HTML code quality
  CHANGELOG.md
  manifest.json
  react/components/MiniCartContent.js
  react/index.js
Labels: chore

#106 Fix Warnings
  CHANGELOG.md
  manifest.json
  react/propTypes.js
Labels: bug

#107 Fixed: Total discount was not showing, even when enabled
  .prettierrc
  CHANGELOG.md
  manifest.json
  react/__mocks__/@vtex/product-details.js
  react/__mocks__/render.js
  react/components/Image.js
  react/components/MiniCartContent.js
  react/components/MiniCartFooter.js
  react/components/Popup.js
  react/components/Sidebar.js
  react/index.js
  react/tests-setup.js
  react/utils/__tests__/itemsHelper.test.js
  react/utils/itemsHelper.js
  react/utils/urlHelpers.js
Labels: bug
